name: daily
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  qr_flutter: ^3.0.1
  oktoast: ^2.3.2
  sqflite: ^1.3.0
  unicorndial: ^1.1.5
  image_picker: ^0.6.7+4
  flutter_swiper: ^1.1.6
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2
  webview_flutter: ^0.3.22+1
  easy_localization: ^2.0.2
  cached_network_image: ^2.0.0
  image_picker_saver: ^0.3.0
  syncfusion_flutter_datepicker: ^18.2.55-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/app.png
    - assets/images/air.png
    - assets/images/email.png
    - assets/images/list.png

  # 字体图标
  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: Conspired
      fonts:
        - asset: assets/fonts/conspired-lovers.woff.ttf
    - family: Dongqing
      fonts:
        - asset: assets/fonts/DongQingHeiTi.otf
