name: daily
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^2.3.2
  flutter_swiper: ^1.1.6
  cupertino_icons: ^0.1.3
  easy_localization: ^2.0.2
  cached_network_image: ^2.0.0
  syncfusion_flutter_datepicker: ^18.2.55-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # 字体图标
  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: Conspired
      fonts:
        - asset: assets/fonts/conspired-lovers.woff.ttf
    - family: Dongqing
      fonts:
        - asset: assets/fonts/DongQingHeiTi.otf
